before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/prom
    ldflags:
      - -w -s
      - -X "github.com/fgouteroux/prom/internal/version.PlatformName={{.Os}}/{{.Arch}}"
      - -X "github.com/fgouteroux/prom/internal/version.GitCommit={{.Commit}}"
      - -X "github.com/fgouteroux/prom/internal/version.BuildTime={{.Date}}"
      - -X "github.com/fgouteroux/prom/internal/version.Version={{.Version}}"
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
